server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:${server.port}/eureka/
  # 注册中心的自我保护，当注册应用下线时立即下线，开发环境使用，生产环境不使用
  server:
    enable-self-preservation: false